"""Panaikiti nereikalingi importai

Revision ID: 82622d5a13de
Revises: 7e442842b052
Create Date: 2025-05-13 21:49:31.062123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '82622d5a13de'
down_revision: Union[str, None] = '7e442842b052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_title', sa.String(length=255), nullable=False))
    op.drop_column('companies', 'company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('companies', 'company_title')
    # ### end Alembic commands ###
