"""Lenteles Sukurimas ir rysio pridejimas

Revision ID: ea13f14c13ec
Revises: fb69bb2d8176
Create Date: 2025-05-13 22:29:42.131879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea13f14c13ec'
down_revision: Union[str, None] = 'fb69bb2d8176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('positions', sa.Column('requirements_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'positions', 'position_requirements', ['requirements_id'], ['id'])
    op.drop_column('positions', 'requirements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('requirements', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_column('positions', 'requirements_id')
    op.drop_table('position_requirements')
    # ### end Alembic commands ###
