"""Lenteles Sukurimas

Revision ID: fb69bb2d8176
Revises: 82622d5a13de
Create Date: 2025-05-13 22:13:55.272772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb69bb2d8176'
down_revision: Union[str, None] = '82622d5a13de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('positions', sa.Column('level_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'positions', 'position_levels', ['level_id'], ['id'])
    op.drop_column('positions', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('level', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_column('positions', 'level_id')
    op.drop_table('position_levels')
    # ### end Alembic commands ###
